### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-reindeer#2]
# User Stories
- [ ] As a user, when I am unauthenticated I should be able to see the dashboard (Read only).
- [ ] As a user, when I am authenticated I should be able to perform all actions on the dashboard (full CRUD).
- [ ] As a user, I should be able to login via google.
- [ ] As a user, I should be able to logout.

**Comment by spotmonk** [comment]
This is how it'll look when you hit the site and you're not logged in

![loggedout](https://user-images.githubusercontent.com/42584830/87373088-a08df400-c54e-11ea-947b-69d990bcb24a.png)

**Comment by spotmonk** [comment]
![image](https://user-images.githubusercontent.com/18632556/87487531-8530f080-c603-11ea-8531-84e3fe1ee80d.png)

**Comment by spotmonk** [comment]
When the add button is clicked on a category, a dropdown form will appear to add the new item.
![dropdown](https://user-images.githubusercontent.com/42584830/87373824-05961980-c550-11ea-8a60-ba18e6e2a85d.png)
