### ISSUE TITLE
Chaos Monkey

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-reindeer#3]
# User Stories
- [ ] As a user, I should be shown a toast whenever the Chaos Monkey strikes
- [ ] As a user, I should allow the Chaos Monkey to do one random act for a set interval
- [ ] As a user, the Chaos Monkey should have a chance to break down a random ride
- [ ] As a user, the Chaos Monkey should have a chance to kidnap a random staff member
- [ ] As a user, the Chaos Monkey should have a chance to break a random piece of equipment

**Comment by spotmonk** [comment]
![image](https://user-images.githubusercontent.com/18632556/87488379-d04c0300-c605-11ea-96eb-2ab4a87dd40f.png)
![image](https://user-images.githubusercontent.com/18632556/87488669-99c2b800-c606-11ea-8210-2753ff5aa0e3.png)

**Comment by nrg51098** [comment]
![image](https://user-images.githubusercontent.com/18632556/87489139-d7741080-c607-11ea-8ce4-b0a3ad6691eb.png)
