### ISSUE TITLE
Equipment Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-reindeer#4]
# User Stories
- [ ] As a user, I should be able to add new equipment
- [ ] As a user, I should be able to delete equipment
- [ ] As a user, I should be able to edit the equipment
- [ ] As a user, I should be able to view all the equipment

**Comment by spotmonk** [comment]
each equpiment card will have this data:
![EquipmentCard](https://user-images.githubusercontent.com/42584830/87373270-ffec0400-c54e-11ea-9db1-b2c324b82609.png)
