### ISSUE TITLE
Vendors Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-reindeer#5]
# User Stories
- [ ] As a user, I should be able to add new vendors
- [ ] As a user, I should be able to delete vendors
- [ ] As a user, I should be able to edit the vendors
- [ ] As a user, I should be able to view all the vendors

**Comment by spotmonk** [comment]
vendor cards will have this info: 
![vendorCard](https://user-images.githubusercontent.com/42584830/87373322-172af180-c54f-11ea-902a-8d1808539112.png)
