### ISSUE TITLE
Rides Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-reindeer#6]
# User Stories
- [ ] As a user, I should be able to add new rides
- [ ] As a user, I should be able to delete rides
- [ ] As a user, I should be able to edit the rides
- [ ] As a user, I should be able to view all the rides

**Comment by spotmonk** [comment]
each card from issue #2 for the rides will have 
![RideCard](https://user-images.githubusercontent.com/42584830/87373368-3295fc80-c54f-11ea-9fb8-9edef8a0d103.png)
