### ISSUE TITLE
Staff Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-reindeer#7]
# User Stories
- [ ] As a user, I should be able to add new staff
- [ ] As a user, I should be able to delete staff
- [ ] As a user, I should be able to edit the staff
- [ ] As a user, I should be able to view all the staff

**Comment by spotmonk** [comment]
Staff cards will have: 
![StaffCard](https://user-images.githubusercontent.com/42584830/87373403-40e41880-c54f-11ea-8a0a-b398fdc591a1.png)
