### ISSUE TITLE
Dinosaurs Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-reindeer#8]
# User Stories
- [ ] As a user, I should be able to add new dinosaurs
- [ ] As a user, I should be able to delete dinosaurs
- [ ] As a user, I should be able to edit the dinosaurs
- [ ] As a user, I should be able to view all the dinosaurs

**Comment by spotmonk** [comment]
dinosaur cards will have: 
![Dinocard](https://user-images.githubusercontent.com/42584830/87373428-50636180-c54f-11ea-89f4-5273c89c31c3.png)
