### ISSUE TITLE
Dinosaur has less than 2 handlers alert

### ISSUE THREAD

**Issue by petestewart** [nss-evening-cohort-12/nutshell-reindeer#92]
## User Story
As a user, I should be alerted whenever there is a dinosaur that has less than 2 handlers

## AC
WHEN a dino has less than 2 handlers
THEN I should see an alert

## Dev Notes
- create function that checks for all dinos with less than 2 handlers
- call that function whenever anything happens that changes staff assignment
- create modal to alert user of situation

**Comment by ryanbeiden** [comment]
This is almost complete!

As of right now, the modal displays if there are dinos that have 1 or less handler. You can update the Staff member to become a handler and the modal updates. The last few things I need to do:

1. Reprint just the `modal-body` and don't clear the modal and run it every time a Dino handler is updated.

2. Add the `checkDinoHandlers` function to all functions that make staff assignment updates.
